#ifndef AUTOMATA_ENGINE_H
#define AUTOMATA_ENGINE_H

#define AUTOMATA_VERSION_TYPE 'A'
#define AUTOMATA_VERSION_MAJOR 1
#define AUTOMATA_VERSION_MINOR 0 
#define AUTOMATA_VERSION_FIX 0

#endif