#ifndef AUTOMATA_INPUT_H
#define AUTOMATA_INPUT_H

#include <glfw/glfw3.h>

/* constant */
#define AUTOMATA_INPUT_KEYS_AMOUNT 440
#define AUTOMATA_INPUT_AXIS_AMOUNT 50
#define AUTOMATA_INPUT_LAST_KEYBOARD_KEY GLFW_KEY_LAST
#define AUTOMATA_INPUT_LAST_MOUSE_BUTTON AUTOMATA_KEY_MOUSE_8
#define AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON AUTOMATA_KEY_GAMEPAD1_DPAD_LEFT
#define AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON AUTOMATA_KEY_GAMEPAD2_DPAD_LEFT
#define AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON AUTOMATA_KEY_GAMEPAD3_DPAD_LEFT
#define AUTOMATA_INPUT_LAST_GAMEPAD4_BUTTON AUTOMATA_KEY_GAMEPAD4_DPAD_LEFT

/* GLFW defines, remove this when 3.3 is released */
#define GLFW_GAMEPAD_BUTTON_A 0
#define GLFW_GAMEPAD_BUTTON_B 1
#define GLFW_GAMEPAD_BUTTON_X 2
#define GLFW_GAMEPAD_BUTTON_Y 3
#define GLFW_GAMEPAD_BUTTON_LEFT_BUMPER 4
#define GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER 5
#define GLFW_GAMEPAD_BUTTON_BACK 6
#define GLFW_GAMEPAD_BUTTON_START 7
#define GLFW_GAMEPAD_BUTTON_GUIDE 8
#define GLFW_GAMEPAD_BUTTON_LEFT_THUMB 9
#define GLFW_GAMEPAD_BUTTON_RIGHT_THUMB 10
#define GLFW_GAMEPAD_BUTTON_DPAD_UP 11
#define GLFW_GAMEPAD_BUTTON_DPAD_RIGHT 12
#define GLFW_GAMEPAD_BUTTON_DPAD_DOWN 13
#define GLFW_GAMEPAD_BUTTON_DPAD_LEFT 14
#define GLFW_GAMEPAD_BUTTON_LAST GLFW_GAMEPAD_BUTTON_DPAD_LEFT
#define GLFW_GAMEPAD_BUTTON_CROSS GLFW_GAMEPAD_BUTTON_A
#define GLFW_GAMEPAD_BUTTON_CIRCLE GLFW_GAMEPAD_BUTTON_B
#define GLFW_GAMEPAD_BUTTON_SQUARE GLFW_GAMEPAD_BUTTON_X
#define GLFW_GAMEPAD_BUTTON_TRIANGLE GLFW_GAMEPAD_BUTTON_Y

/* data structures */
typedef enum AutomataInputKey {
	/* keypad */
	AUTOMATA_KEY_KP_0			= GLFW_KEY_KP_0,
	AUTOMATA_KEY_KP_1			= GLFW_KEY_KP_1,
	AUTOMATA_KEY_KP_2			= GLFW_KEY_KP_2,
	AUTOMATA_KEY_KP_3			= GLFW_KEY_KP_3,
	AUTOMATA_KEY_KP_4			= GLFW_KEY_KP_4,
	AUTOMATA_KEY_KP_5			= GLFW_KEY_KP_5,
	AUTOMATA_KEY_KP_6			= GLFW_KEY_KP_6,
	AUTOMATA_KEY_KP_7			= GLFW_KEY_KP_7,
	AUTOMATA_KEY_KP_8			= GLFW_KEY_KP_8,
	AUTOMATA_KEY_KP_9			= GLFW_KEY_KP_9,
	AUTOMATA_KEY_KP_DECIMAL		= GLFW_KEY_KP_DECIMAL,
	AUTOMATA_KEY_KP_DIVIDE		= GLFW_KEY_KP_DIVIDE,
	AUTOMATA_KEY_KP_MULTIPLY	= GLFW_KEY_KP_MULTIPLY,
	AUTOMATA_KEY_KP_SUBTRACT	= GLFW_KEY_KP_SUBTRACT,
	AUTOMATA_KEY_KP_ADD			= GLFW_KEY_KP_ADD,
	AUTOMATA_KEY_KP_ENTER		= GLFW_KEY_KP_ENTER,
	AUTOMATA_KEY_KP_EQUAL		= GLFW_KEY_KP_EQUAL,

	AUTOMATA_KEY_UNKNOWN = GLFW_KEY_UNKNOWN,
	
	/* numbers */
	AUTOMATA_KEY_0 = GLFW_KEY_0,
	AUTOMATA_KEY_1 = GLFW_KEY_1,
	AUTOMATA_KEY_2 = GLFW_KEY_2,
	AUTOMATA_KEY_3 = GLFW_KEY_3,
	AUTOMATA_KEY_4 = GLFW_KEY_4,
	AUTOMATA_KEY_5 = GLFW_KEY_5,
	AUTOMATA_KEY_6 = GLFW_KEY_6,
	AUTOMATA_KEY_7 = GLFW_KEY_7,
	AUTOMATA_KEY_8 = GLFW_KEY_8,
	AUTOMATA_KEY_9 = GLFW_KEY_9,
	
	/* function keys */
	AUTOMATA_KEY_F1 = GLFW_KEY_F1,
	AUTOMATA_KEY_F2 = GLFW_KEY_F2,
	AUTOMATA_KEY_F3 = GLFW_KEY_F3,
	AUTOMATA_KEY_F4 = GLFW_KEY_F4,
	AUTOMATA_KEY_F5 = GLFW_KEY_F5,
	AUTOMATA_KEY_F6 = GLFW_KEY_F6,
	AUTOMATA_KEY_F7 = GLFW_KEY_F7,
	AUTOMATA_KEY_F8 = GLFW_KEY_F8,
	AUTOMATA_KEY_F9 = GLFW_KEY_F9,
	AUTOMATA_KEY_F10 = GLFW_KEY_F10,
	AUTOMATA_KEY_F11 = GLFW_KEY_F11,
	AUTOMATA_KEY_F12 = GLFW_KEY_F12,

	/* letters */
	AUTOMATA_KEY_A = GLFW_KEY_A,
	AUTOMATA_KEY_B = GLFW_KEY_B,
	AUTOMATA_KEY_C = GLFW_KEY_C,
	AUTOMATA_KEY_D = GLFW_KEY_D,
	AUTOMATA_KEY_E = GLFW_KEY_E,
	AUTOMATA_KEY_F = GLFW_KEY_F,
	AUTOMATA_KEY_G = GLFW_KEY_G,
	AUTOMATA_KEY_H = GLFW_KEY_H,
	AUTOMATA_KEY_I = GLFW_KEY_I,
	AUTOMATA_KEY_J = GLFW_KEY_J,
	AUTOMATA_KEY_K = GLFW_KEY_K,
	AUTOMATA_KEY_L = GLFW_KEY_L,
	AUTOMATA_KEY_M = GLFW_KEY_M,
	AUTOMATA_KEY_N = GLFW_KEY_N,
	AUTOMATA_KEY_O = GLFW_KEY_O,
	AUTOMATA_KEY_P = GLFW_KEY_P,
	AUTOMATA_KEY_Q = GLFW_KEY_Q,
	AUTOMATA_KEY_R = GLFW_KEY_R,
	AUTOMATA_KEY_S = GLFW_KEY_S,
	AUTOMATA_KEY_T = GLFW_KEY_T,
	AUTOMATA_KEY_U = GLFW_KEY_U,
	AUTOMATA_KEY_V = GLFW_KEY_V,
	AUTOMATA_KEY_W = GLFW_KEY_W,
	AUTOMATA_KEY_X = GLFW_KEY_X,
	AUTOMATA_KEY_Y = GLFW_KEY_Y,
	AUTOMATA_KEY_Z = GLFW_KEY_Z,

	/* special keys */
	AUTOMATA_KEY_UP				= GLFW_KEY_UP,
	AUTOMATA_KEY_DOWN			= GLFW_KEY_DOWN,
	AUTOMATA_KEY_LEFT			= GLFW_KEY_LEFT,
	AUTOMATA_KEY_RIGHT			= GLFW_KEY_RIGHT,
	AUTOMATA_KEY_SPACE			= GLFW_KEY_SPACE,
	AUTOMATA_KEY_ENTER			= GLFW_KEY_ENTER,
	AUTOMATA_KEY_ESC			= GLFW_KEY_ESCAPE,
	AUTOMATA_KEY_TAB			= GLFW_KEY_TAB,
	AUTOMATA_KEY_LCTRL			= GLFW_KEY_LEFT_CONTROL,
	AUTOMATA_KEY_RCTRL			= GLFW_KEY_RIGHT_CONTROL,
	AUTOMATA_KEY_LSHIFT			= GLFW_KEY_LEFT_SHIFT,
	AUTOMATA_KEY_RSHIFT			= GLFW_KEY_RIGHT_SHIFT,
	AUTOMATA_KEY_LALT			= GLFW_KEY_LEFT_ALT,
	AUTOMATA_KEY_RALT			= GLFW_KEY_RIGHT_ALT,
	AUTOMATA_KEY_LBRACKET		= GLFW_KEY_LEFT_BRACKET,
	AUTOMATA_KEY_RBRACKET		= GLFW_KEY_RIGHT_BRACKET,
	AUTOMATA_KEY_LSUPER			= GLFW_KEY_LEFT_SUPER,
	AUTOMATA_KEY_RSUPER			= GLFW_KEY_RIGHT_SUPER,
	AUTOMATA_KEY_QOUTE			= GLFW_KEY_APOSTROPHE,
	AUTOMATA_KEY_COMMA			= GLFW_KEY_COMMA,
	AUTOMATA_KEY_MINUS			= GLFW_KEY_MINUS,
	AUTOMATA_KEY_PERIOD			= GLFW_KEY_PERIOD,
	AUTOMATA_KEY_SLASH			= GLFW_KEY_SLASH,
	AUTOMATA_KEY_SEMICOLON		= GLFW_KEY_SEMICOLON,
	AUTOMATA_KEY_EQUAL			= GLFW_KEY_EQUAL,
	AUTOMATA_KEY_BACSLASH		= GLFW_KEY_BACKSLASH,
	AUTOMATA_KEY_GRAVE_ACCENT	= GLFW_KEY_GRAVE_ACCENT,
	AUTOMATA_KEY_WORLD1			= GLFW_KEY_WORLD_1,
	AUTOMATA_KEY_WORLD2			= GLFW_KEY_WORLD_2,
	AUTOMATA_KEY_BACKSPACE		= GLFW_KEY_BACKSPACE,
	AUTOMATA_KEY_INSERT			= GLFW_KEY_INSERT,
	AUTOMATA_KEY_DELETE			= GLFW_KEY_DELETE,
	AUTOMATA_KEY_PAGEUP			= GLFW_KEY_PAGE_UP,
	AUTOMATA_KEY_PAGEDOWN		= GLFW_KEY_PAGE_DOWN,
	AUTOMATA_KEY_HOME			= GLFW_KEY_HOME,
	AUTOMATA_KEY_END			= GLFW_KEY_END,
	AUTOMATA_KEY_CAPSLOCK		= GLFW_KEY_CAPS_LOCK,
	AUTOMATA_KEY_SCROLLLOCK		= GLFW_KEY_SCROLL_LOCK,
	AUTOMATA_KEY_NUMLOCK		= GLFW_KEY_NUM_LOCK,
	AUTOMATA_KEY_PRINTSCREEN	= GLFW_KEY_PRINT_SCREEN,
	AUTOMATA_KEY_PAUSE			= GLFW_KEY_PAUSE,
	AUTOMATA_KEY_MENU			= GLFW_KEY_MENU,

	/* mouse buttons */
	AUTOMATA_KEY_MOUSE_1 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_1,
	AUTOMATA_KEY_MOUSE_2 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_2,
	AUTOMATA_KEY_MOUSE_3 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_3,
	AUTOMATA_KEY_MOUSE_4 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_4,
	AUTOMATA_KEY_MOUSE_5 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_5,
	AUTOMATA_KEY_MOUSE_6 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_6,
	AUTOMATA_KEY_MOUSE_7 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_7,
	AUTOMATA_KEY_MOUSE_8 = (AUTOMATA_INPUT_LAST_KEYBOARD_KEY + 1) + GLFW_MOUSE_BUTTON_8,

	/* gamepad 1 */
	AUTOMATA_KEY_GAMEPAD1_A				= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_A,
	AUTOMATA_KEY_GAMEPAD1_B				= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_B,
	AUTOMATA_KEY_GAMEPAD1_X				= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_X,
	AUTOMATA_KEY_GAMEPAD1_Y				= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_Y,
	AUTOMATA_KEY_GAMEPAD1_RBUMPER		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
	AUTOMATA_KEY_GAMEPAD1_LBUMPER		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
	AUTOMATA_KEY_GAMEPAD1_BACK			= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_BACK,
	AUTOMATA_KEY_GAMEPAD1_START			= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_START,
	AUTOMATA_KEY_GAMEPAD1_GUIDE			= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_GUIDE,
	AUTOMATA_KEY_GAMEPAD1_LTHUMB		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
	AUTOMATA_KEY_GAMEPAD1_RTHUMB		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
	AUTOMATA_KEY_GAMEPAD1_DPAD_UP		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_UP,
	AUTOMATA_KEY_GAMEPAD1_DPAD_RIGHT	= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
	AUTOMATA_KEY_GAMEPAD1_DPAD_DOWN		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
	AUTOMATA_KEY_GAMEPAD1_DPAD_LEFT		= (AUTOMATA_INPUT_LAST_MOUSE_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_LEFT,

	/* gamepad 2 */
	AUTOMATA_KEY_GAMEPAD2_A				= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_A,
	AUTOMATA_KEY_GAMEPAD2_B				= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_B,
	AUTOMATA_KEY_GAMEPAD2_X				= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_X,
	AUTOMATA_KEY_GAMEPAD2_Y				= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_Y,
	AUTOMATA_KEY_GAMEPAD2_RBUMPER		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
	AUTOMATA_KEY_GAMEPAD2_LBUMPER		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
	AUTOMATA_KEY_GAMEPAD2_BACK			= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_BACK,
	AUTOMATA_KEY_GAMEPAD2_START			= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_START,
	AUTOMATA_KEY_GAMEPAD2_GUIDE			= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_GUIDE,
	AUTOMATA_KEY_GAMEPAD2_LTHUMB		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
	AUTOMATA_KEY_GAMEPAD2_RTHUMB		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
	AUTOMATA_KEY_GAMEPAD2_DPAD_UP		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_UP,
	AUTOMATA_KEY_GAMEPAD2_DPAD_RIGHT	= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
	AUTOMATA_KEY_GAMEPAD2_DPAD_DOWN		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
	AUTOMATA_KEY_GAMEPAD2_DPAD_LEFT		= (AUTOMATA_INPUT_LAST_GAMEPAD1_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_LEFT,

	/* gamepad 3 */
	AUTOMATA_KEY_GAMEPAD3_A				= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_A,
	AUTOMATA_KEY_GAMEPAD3_B				= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_B,
	AUTOMATA_KEY_GAMEPAD3_X				= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_X,
	AUTOMATA_KEY_GAMEPAD3_Y				= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_Y,
	AUTOMATA_KEY_GAMEPAD3_RBUMPER		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
	AUTOMATA_KEY_GAMEPAD3_LBUMPER		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
	AUTOMATA_KEY_GAMEPAD3_BACK			= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_BACK,
	AUTOMATA_KEY_GAMEPAD3_START			= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_START,
	AUTOMATA_KEY_GAMEPAD3_GUIDE			= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_GUIDE,
	AUTOMATA_KEY_GAMEPAD3_LTHUMB		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
	AUTOMATA_KEY_GAMEPAD3_RTHUMB		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
	AUTOMATA_KEY_GAMEPAD3_DPAD_UP		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_UP,
	AUTOMATA_KEY_GAMEPAD3_DPAD_RIGHT	= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
	AUTOMATA_KEY_GAMEPAD3_DPAD_DOWN		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
	AUTOMATA_KEY_GAMEPAD3_DPAD_LEFT		= (AUTOMATA_INPUT_LAST_GAMEPAD2_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_LEFT,

	/* gamepad 4 */
	AUTOMATA_KEY_GAMEPAD4_A				= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_A,
	AUTOMATA_KEY_GAMEPAD4_B				= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_B,
	AUTOMATA_KEY_GAMEPAD4_X				= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_X,
	AUTOMATA_KEY_GAMEPAD4_Y				= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_Y,
	AUTOMATA_KEY_GAMEPAD4_RBUMPER		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
	AUTOMATA_KEY_GAMEPAD4_LBUMPER		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
	AUTOMATA_KEY_GAMEPAD4_BACK			= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_BACK,
	AUTOMATA_KEY_GAMEPAD4_START			= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_START,
	AUTOMATA_KEY_GAMEPAD4_GUIDE			= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_GUIDE,
	AUTOMATA_KEY_GAMEPAD4_LTHUMB		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
	AUTOMATA_KEY_GAMEPAD4_RTHUMB		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
	AUTOMATA_KEY_GAMEPAD4_DPAD_UP		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_UP,
	AUTOMATA_KEY_GAMEPAD4_DPAD_RIGHT	= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
	AUTOMATA_KEY_GAMEPAD4_DPAD_DOWN		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
	AUTOMATA_KEY_GAMEPAD4_DPAD_LEFT		= (AUTOMATA_INPUT_LAST_GAMEPAD3_BUTTON + 1) + GLFW_GAMEPAD_BUTTON_DPAD_LEFT,
} AutomataInputKey;

typedef enum AutomataInputAxis {
	AUTOMATA_AXIS_MOUSE_X = 0,
	AUTOMATA_AXIS_MOUSE_Y,
	AUTOMATA_AXIS_GAMEPAD1_LTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD1_LTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD1_RTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD1_RTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD1_LTRIGGER,
	AUTOMATA_AXIS_GAMEPAD1_RTRIGGER,
	AUTOMATA_AXIS_GAMEPAD2_LTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD2_LTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD2_RTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD2_RTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD2_LTRIGGER,
	AUTOMATA_AXIS_GAMEPAD2_RTRIGGER,
	AUTOMATA_AXIS_GAMEPAD3_LTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD3_LTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD3_RTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD3_RTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD3_LTRIGGER,
	AUTOMATA_AXIS_GAMEPAD3_RTRIGGER,
	AUTOMATA_AXIS_GAMEPAD4_LTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD4_LTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD4_RTHUMB_X,
	AUTOMATA_AXIS_GAMEPAD4_RTHUMB_Y,
	AUTOMATA_AXIS_GAMEPAD4_LTRIGGER,
	AUTOMATA_AXIS_GAMEPAD4_RTRIGGER,
} AutomataInputAxis;

/* functions */
int automataInputGetKey(AutomataInputKey key);
int automataInputGetAnyKey();
double automataInputGetAxis(AutomataInputAxis axis);

/* callbacks */
void automataInputKeyboardKeyCallback(GLFWwindow *glfwWindow, int key, int scancode, int action, int mods);
void automataInputMouseButtonCallback(GLFWwindow *glfwWindow, int button, int action, int mods);
void automataInputMousePositionCallback(GLFWwindow *glfwWindow, double xpos, double ypos);

#endif