#ifndef AUTOMATA_NETWORK_H
#define AUTOMATA_NETWORK_H

#define AUTOMATA_NETWORK_SERVER_MAX_CLIENTS 32
#define AUTOMATA_NETWORK_DEFAULT_IP "127.0.0.1"
#define AUTOMATA_NETWORK_DEFAULT_PORT 27015
#define AUTOMATA_NETWORK_DEFAULT_CONNECTIONS AUTOMATA_NETWORK_SERVER_MAX_CLIENTS

/* data structures */

/* functions */

#endif